# POS IESB 2020 - Disciplina Fundamentos de IA
# Trabalho 01

## Aluno: Eduardo Gomes Piza
## Aluno: Valter Takechi Hada

### Utilizando a toolbox de sua preferência, realize o treinamento de uma rede neural artificial do tipo   Perceptron Multicamadas para resolver um problema de classificação multiclasses.

### Informações: Utilizamos um dos datasets constantes no site "archive.ics.uci/edu" (conforme sugestão) cujo conteúdo está relacionado a "Early stage diabetes risk prediction dataset" (dados para previsão de risco de diabetes em estagio inicial). 

### Dados adicionais quanto ao dataset e arquivo .csv podem ser verificados através da url "http://archive.ics.uci.edu/ml/datasets/Early+stage+diabetes+risk+prediction+dataset."

### O dataset contém respostas de um questionário respondido por pacientes do "Sylhet Diabetes Hospital", em Bangladesh, e foi aprovado por médico/especialista.

In [1]:
# Passo 1
# Vamos importar o dataset com os dados que serão utilizados

import pandas as pd

uri = "http://archive.ics.uci.edu/ml/machine-learning-databases/00529/diabetes_data_upload.csv"
#uri = "diabetes_data_upload.csv"
dados_input = pd.read_csv(uri)
dados_input.head()

Age Gender Polyuria Polydipsia sudden weight loss weakness Polyphagia  \
0   40   Male       No        Yes                 No      Yes         No   
1   58   Male       No         No                 No      Yes         No   
2   41   Male      Yes         No                 No      Yes        Yes   
3   45   Male       No         No                Yes      Yes        Yes   
4   60   Male      Yes        Yes                Yes      Yes        Yes   

  Genital thrush visual blurring Itching Irritability delayed healing  \
0             No              No     Yes           No             Yes   
1             No             Yes      No           No              No   
2             No              No     Yes           No             Yes   
3            Yes              No     Yes           No             Yes   
4             No             Yes     Yes          Yes             Yes   

  partial paresis muscle stiffness Alopecia Obesity     class  
0              No              Yes      Yes     Yes  Positive  
1             Yes               No      Yes      No  Positive  
2              No              Yes      Yes      No  Positive  
3              No               No       No      No  Positive  
4             Yes              Yes      Yes     Yes  Positive

In [2]:
# Passo 2
# Vamos atualizar todo o data set renomeando as colunas com o termo traduzido

cabecalho = { 
    "Age" : "Idade",
    "Gender" : "Sexo",
    "Polyuria" : "Poliuria",
    "Polydipsia" : "Polidipsia",
    "sudden weight loss" : "Perda_subita_de_peso",
    "weakness" : "Fraqueza",
    "Polyphagia" : "Polifagia",
    "Genital thrush" : "Herpes_genital",
    "visual blurring" : "Visao_borrada",
    "Itching" : "Coceira",
    "Irritability" : "Irritabilidade",
    "delayed healing" : "Cicatrizacao_lenta",
    "partial paresis" : "Paralisia_parcial",
    "muscle stiffness" : "Rigidez_muscular",
    "Alopecia" : "Calvicie",
    "Obesity" : "Obesidade",
    "class" : "Situacao"
}
dados_input = dados_input.rename(columns = cabecalho)
dados_input.head()

Idade  Sexo Poliuria Polidipsia Perda_subita_de_peso Fraqueza Polifagia  \
0     40  Male       No        Yes                   No      Yes        No   
1     58  Male       No         No                   No      Yes        No   
2     41  Male      Yes         No                   No      Yes       Yes   
3     45  Male       No         No                  Yes      Yes       Yes   
4     60  Male      Yes        Yes                  Yes      Yes       Yes   

  Herpes_genital Visao_borrada Coceira Irritabilidade Cicatrizacao_lenta  \
0             No            No     Yes             No                Yes   
1             No           Yes      No             No                 No   
2             No            No     Yes             No                Yes   
3            Yes            No     Yes             No                Yes   
4             No           Yes     Yes            Yes                Yes   

  Paralisia_parcial Rigidez_muscular Calvicie Obesidade  Situacao  
0                No              Yes      Yes       Yes  Positive  
1               Yes               No      Yes        No  Positive  
2                No              Yes      Yes        No  Positive  
3                No               No       No        No  Positive  
4               Yes              Yes      Yes       Yes  Positive

In [3]:
# Passo 3
# Vamos atualizar o conteudo das linhas, transformando o conteúdo em números:

converte_sexo = { "Male" : 1,
                  "Female" : 0 }

dados_input['Sexo'] = dados_input.Sexo.map(converte_sexo)

converte_resp = { "No" : 0,
                  "Yes" : 1 }

dados_input['Poliuria'] = dados_input.Poliuria.map(converte_resp)
dados_input['Polidipsia'] = dados_input.Polidipsia.map(converte_resp)
dados_input['Perda_subita_de_peso'] = dados_input.Perda_subita_de_peso.map(converte_resp)
dados_input['Fraqueza'] = dados_input.Fraqueza.map(converte_resp)
dados_input['Polifagia'] = dados_input.Polifagia.map(converte_resp)
dados_input['Herpes_genital'] = dados_input.Herpes_genital.map(converte_resp)
dados_input['Visao_borrada'] = dados_input.Visao_borrada.map(converte_resp)
dados_input['Coceira'] = dados_input.Coceira.map(converte_resp)
dados_input['Irritabilidade'] = dados_input.Irritabilidade.map(converte_resp)
dados_input['Cicatrizacao_lenta'] = dados_input.Cicatrizacao_lenta.map(converte_resp)
dados_input['Paralisia_parcial'] = dados_input.Paralisia_parcial.map(converte_resp)
dados_input['Rigidez_muscular'] = dados_input.Rigidez_muscular.map(converte_resp)
dados_input['Calvicie'] = dados_input.Calvicie.map(converte_resp)
dados_input['Obesidade'] = dados_input.Obesidade.map(converte_resp)

converte_situacao = { "Positive" : 1,
                      "Negative" : 0}

dados_input['Situacao'] = dados_input.Situacao.map(converte_situacao)

dados_input.tail()

Idade  Sexo  Poliuria  Polidipsia  Perda_subita_de_peso  Fraqueza  \
515     39     0         1           1                     1         0   
516     48     0         1           1                     1         1   
517     58     0         1           1                     1         1   
518     32     0         0           0                     0         1   
519     42     1         0           0                     0         0   

     Polifagia  Herpes_genital  Visao_borrada  Coceira  Irritabilidade  \
515          1               0              0        1               0   
516          1               0              0        1               1   
517          1               0              1        0               0   
518          0               0              1        1               0   
519          0               0              0        0               0   

     Cicatrizacao_lenta  Paralisia_parcial  Rigidez_muscular  Calvicie  \
515                   1                  1                 0         0   
516                   1                  1                 0         0   
517                   0                  1                 1         0   
518                   1                  0                 0         1   
519                   0                  0                 0         0   

     Obesidade  Situacao  
515          0         1  
516          0         1  
517          1         1  
518          0         0  
519          0         0

In [4]:
# Passo 4
# Uma vez que os dados foram tratados vamos ordená-los de forma aleatória, 
# separar as colunas de classificação (features) e a coluna de resultado, e
# ajustar o tipo de dado para usá-lo como input dos procedimentos.

import numpy as np
#from sklearn.utils import shuffle
#dados_input = shuffle(dados_input)

x = dados_input[['Idade', 
                 'Sexo',
                 'Poliuria',
                 'Polidipsia',
                 'Perda_subita_de_peso',
                 'Fraqueza',
                 'Polifagia',
                 'Herpes_genital',
                 'Visao_borrada',
                 'Coceira',
                 'Irritabilidade',
                 'Cicatrizacao_lenta',
                 'Paralisia_parcial',
                 'Rigidez_muscular',
                 'Calvicie',
                 'Obesidade']]

y = dados_input[['Situacao']]

# Setando a tipagem do conteudo como inteiro
x = x.astype(np.uint8)
y = y.astype(np.uint8)

# convertendo de 'pandas.dataframe' para 'numpy.ndarray'
x = x.to_numpy(copy=True)
y = y.to_numpy(copy=True)

print(type(x))
print(x.shape)
print(type(y))
print(y.shape)

<class 'numpy.ndarray'>
(520, 16)
<class 'numpy.ndarray'>
(520, 1)


In [5]:
# Passo 05
# Agora vamos separar o data set para termos os dados de TREINO e TESTE, 
# ordenando-os de forma aleatória e garantindo que os registros selecionados
# para teste apresentem a mesma proporção que os registros de treino para 
# a 'SITUACAO' (que indica se o paciente possui ou nao diabetes) . Vamos 
# separar 80% dos registros para treino e 20% para testes. 

# Para separacao dos grupos de treino e teste usando 'train_test_split'
from sklearn.model_selection import train_test_split

# métricas
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

# model
from sklearn.neural_network import MLPClassifier

# validação cruzada
from sklearn.model_selection import StratifiedKFold

# matrizes numéricas e plot
import numpy as np
from matplotlib import pyplot as plt

# organiza aleatoriamente matrizes 
from sklearn.utils import shuffle

# funcao para recuperacao do timestamp
from time import process_time

# Como vamos usar 'StratifiedKFold' para separar os registros de treino e teste
# nao precisamos executar os procedimentos abaixo, que fariam o mesmo processo
# mas usando a 'train_test_split'
##SEED = 20
##treino_x, teste_x, treino_y, teste_y = train_test_split(x, 
##                                                        y,
##                                                        random_state = SEED, 
##                                                        test_size = 0.10,
##                                                        stratify = y)
##print("Treinaremos com %d elementos e testaremos com %d elementos" % (len(treino_x), len(teste_x)))

# Parametros que serao usados na rede
epocas = 5000

# definindo arquitetura da PMC - com duas camadas intermediárias
mlp = MLPClassifier(hidden_layer_sizes=(128,128,),  # 2 camadas com 128 neurônios cada
                    activation='tanh',              # funcao hiperbolica
                    max_iter=epocas,                # numero maximo de iteracoes
                    alpha=1e-4,                     # restringir o tamanho dos pesos, fator de penalidade
                    solver='lbfgs',                 # algoritmo otimizador (metodo quasi-Newton)
                    verbose=False,                  # nao imprimir mensagens de progresso 
                    tol=1e-5,                       # tolerancia para continuidade da otimizacao
                    n_iter_no_change=10,            # a otimizacao vai parar se nos ultimos 'n' resultados não houver melhora
                    random_state=1,                 # geracao de numeros aleatorios para inicializacao e pesos de bias 
                    learning_rate_init=.001)        # taxa de aprendizagem inicial

# arrays para armazenar o tempo de duracao, acuracia e precisao de cada treino
time_train_mlp =[]
acuracia_mlp = []
precisao_mlp = []

# Validação cruzada com k folds
k = 10 
skf = StratifiedKFold(n_splits=k, random_state=None)

for train_index, test_index in skf.split(x,y): 

    print("Treino: ", train_index)
    print(train_index.shape)
    print("Validacao: ", test_index) 
    print(test_index.shape)
    
    sinais_treinamento, sinais_validacao = x[train_index], x[test_index] 
    labels_treinamento, labels_validacao = y[train_index], y[test_index]
    
    # para garantir serem randomicos, mas com mesmo padrão/ordem -> 'random_state' igual
    x_treinamento, y_treinamento = shuffle(sinais_treinamento, labels_treinamento, random_state = 42)
    x_validacao, y_validacao = shuffle(sinais_validacao, labels_validacao, random_state = 42)

    # Aqui fazer um treinamento de 100 épocas (parametros da MLP) e uma validacao da MLP
    start = process_time()
    mlp.fit(x_treinamento, y_treinamento)
    end = process_time()
    time_mlp = end - start

    # Métricas da validacão mlp
    preds_val_mlp = mlp.predict(x_validacao)  
    cm_val_mlp = confusion_matrix(y_validacao, preds_val_mlp)
    print(cm_val_mlp)
    
    TP = cm_val_mlp[0,0]   # True Positive
    FP = cm_val_mlp[0,1]   # False Positive
    FN = cm_val_mlp[1,0]   # False Negative 
    TN = cm_val_mlp[1,1]   # True Negative  

    acuracia_mlp_ = (TP+TN)*100/(len(y_validacao))
    precisao_mlp_ = TP*100/(TP+FP)
    print('Acuracia apurada neste ciclo: ', acuracia_mlp_)
    print('Precisao apurada neste ciclo: ', precisao_mlp_)

    # Usar no calculo das médias da mlp
    time_train_mlp.append(time_mlp)
    acuracia_mlp.append(acuracia_mlp_)
    precisao_mlp.append(precisao_mlp_)

media_time_train_mlp = sum(time_train_mlp) / float(len(time_train_mlp))
media_acuracia_mlp = sum(acuracia_mlp) / float(len(acuracia_mlp))
media_precisao_mlp = sum(precisao_mlp) / float(len(precisao_mlp))

print('--------------------------------------------------------------------------------')
print('Tempo médio de treinamento MLP com ' + str(k) + ' kfolds - Tempo: ' + str (media_time_train_mlp) + ' segundos.')
print('Médias das Validações com ' + str(k) + ' folds')
print('Acurácia_mlp: ' + str(media_acuracia_mlp))
print('Precisão_mlp: ' + str(media_precisao_mlp))



Treino:  [ 32  33  34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49
  50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85
  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100 101 102 103
 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121
 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139
 140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157
 158 159 160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175
 176 177 178 179 180 181 182 183 184 185 186 187 188 189 190 191 192 193
 194 195 196 197 198 199 220 221 222 223 224 225 226 227 228 229 230 231
 232 233 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249
 250 251 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267
 268 269 270 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285
 286 287 288 289 290 291 292 293 294 295 2

C:\Users\eduar\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


[[19  1]
 [ 3 29]]
Acuracia apurada neste ciclo:  92.3076923076923
Precisao apurada neste ciclo:  95.0
Treino:  [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  64  65  66  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85
  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100 101 102 103
 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121
 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139
 140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157
 158 159 160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175
 176 177 178 179 180 181 182 183 184 185 186 187 188 189 190 191 192 193
 194 195 196 197 198 199 200 201 202 203 204 205 206 207 208 209 210 211
 212 213 214 215 216 217 218 219 240 241 242 243 244 245 246 247 248 249
 250 251 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267
 268 269 270

C:\Users\eduar\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\eduar\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:471: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
C:\Users\eduar\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


[[19  1]
 [ 0 32]]
Acuracia apurada neste ciclo:  98.07692307692308
Precisao apurada neste ciclo:  95.0
Treino:  [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  96  97  98  99 100 101 102 103
 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121
 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139
 140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157
 158 159 160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175
 176 177 178 179 180 181 182 183 184 185 186 187 188 189 190 191 192 193
 194 195 196 197 198 199 200 201 202 203 204 205 206 207 208 209 210 211
 212 213 214 215 216 217 218 219 220 221 222 223 224 225 226 227 228 229
 230 231 232 233 234 235 236 237 238 239 249 250 251 252 253 254 255 256
 257 258 25

C:\Users\eduar\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:471: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
C:\Users\eduar\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


[[19  1]
 [ 2 30]]
Acuracia apurada neste ciclo:  94.23076923076923
Precisao apurada neste ciclo:  95.0
Treino:  [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95 128 129 130 131 132 133 134 135 136 137 138 139
 140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157
 158 159 160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175
 176 177 178 179 180 181 182 183 184 185 186 187 188 189 190 191 192 193
 194 195 196 197 198 199 200 201 202 203 204 205 206 207 208 209 210 211
 212 213 214 215 216 217 218 219 220 221 222 223 224 225 226 227 228 229
 230 231 232 233 234 235 236 237 238 239 240 241 242 243 244 245 246 247
 248 249 25

C:\Users\eduar\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


[[17  3]
 [ 1 31]]
Acuracia apurada neste ciclo:  92.3076923076923
Precisao apurada neste ciclo:  85.0
Treino:  [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 192 193
 194 195 196 197 198 199 200 201 202 203 204 205 206 207 208 209 210 211
 212 213 214 215 216 217 218 219 220 221 222 223 224 225 226 227 228 229
 230 231 232 233 234 235 236 237 238 239 240 241 242 243 244 245 246 247
 248 249 250

C:\Users\eduar\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


[[20  0]
 [ 0 32]]
Acuracia apurada neste ciclo:  100.0
Precisao apurada neste ciclo:  100.0
Treino:  [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 200 201 202 203 204 205
 206 207 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223
 224 225 226 227 228 2

C:\Users\eduar\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


[[20  0]
 [ 0 32]]
Acuracia apurada neste ciclo:  100.0
Precisao apurada neste ciclo:  100.0
Treino:  [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 2

C:\Users\eduar\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


[[20  0]
 [ 0 32]]
Acuracia apurada neste ciclo:  100.0
Precisao apurada neste ciclo:  100.0
Treino:  [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 2

C:\Users\eduar\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


[[20  0]
 [ 0 32]]
Acuracia apurada neste ciclo:  100.0
Precisao apurada neste ciclo:  100.0
Treino:  [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 2

C:\Users\eduar\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


[[18  2]
 [ 0 32]]
Acuracia apurada neste ciclo:  96.15384615384616
Precisao apurada neste ciclo:  90.0
--------------------------------------------------------------------------------
Tempo médio de treinamento MLP com 10 kfolds - Tempo: 177.5453125 segundos.
Médias das Validações com 10 folds
Acurácia_mlp: 97.11538461538461
Precisão_mlp: 96.0


In [24]:
# Passo 06 - Exibir gráfico de perda/loss.
# Nao vamos executar pois apenas o otimizador "sgd" possui a loss function
# (e estamos usando em nossa rede o otimizador "lbfgs")

# loss_values = mlp.loss_curve_
# plt.plot(loss_values)
# plt.show()

In [6]:
from sklearn.model_selection import cross_validate

cv_results = cross_validate(mlp, x_treinamento, y_treinamento, cv=10)

# Retorna a precisao media a partir dos dados (treino e teste) disponibilizados
cv_results['test_score']

C:\Users\eduar\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\eduar\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\eduar\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\eduar\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**

array([0.95744681, 0.95744681, 0.9787234 , 0.9787234 , 0.9787234 ,
       0.91489362, 0.95744681, 0.9787234 , 0.93478261, 0.97826087])

In [ ]:
from sklearn.model_selection import GridSearchCV

parameters = {'activation':('identity', 'logistic', 'tanh', 'relu'), 'tol':[1e-5, 1e-1]}

clf = GridSearchCV(mlp, parameters, cv=10)
clf.fit(x_treinamento, y_treinamento,)

C:\Users\eduar\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\eduar\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\eduar\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\eduar\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**

C:\Users\eduar\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\eduar\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\eduar\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\eduar\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**

In [27]:
clf.cv_results_

{'mean_fit_time': array([0.42765801, 0.09783797, 0.65893798, 0.0310168 , 0.85710866,
        0.12047825, 1.08639562, 0.27656014]),
 'std_fit_time': array([0.02534722, 0.01160066, 0.04286914, 0.0040003 , 0.03430333,
        0.12816384, 0.11489125, 0.11289774]),
 'mean_score_time': array([0.00059872, 0.00069838, 0.00079808, 0.00079796, 0.00119703,
        0.00119672, 0.00109718, 0.00109763]),
 'std_score_time': array([0.00048885, 0.00045719, 0.00039904, 0.00039898, 0.00039921,
        0.00039889, 0.00029954, 0.00029931]),
 'param_activation': masked_array(data=['identity', 'identity', 'logistic', 'logistic', 'tanh',
                    'tanh', 'relu', 'relu'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_tol': masked_array(data=[1e-05, 0.1, 1e-05, 0.1, 1e-05, 0.1, 1e-05, 0.1],
              mask=[False, False, False, False, False, False, False, False],
        fill_value='?',
             dtype=ob

In [ ]:
clf.cv_results_['params'][clf.best_index_]